// app/layout.js
import localFont from "next/font/local";
import { getServerSession } from "next-auth";
import { authOptions } from "./lib/auth";
import SessionProviderWrapper from "./Providers/SessionProvider";
import "./globals.css";


// if using different fonts you can delete those 2 below
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  // if(session){
  //   Signed in as {session.user.email} <br />
  //   <button onClick={() => signOut()}>Sign out</button>
  // }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionProviderWrapper session={session}>

          {/* Nav can go here */}
          {children}
          {/* Footer here */}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
